### PR TITLE
feat:Added RunTime Support for Bunjs

### PR DESCRIPTION
**Pull request by vsvishalsharma**
fixes:#4

Changes Made:

Added BunJS as a dependency in the project's package.json.
Updated project configurations and build scripts to support BunJS runtime.
Tested various functionalities to ensure compatibility with BunJS.

### CODE REVIEW

**Comment by vsvishalsharma** [comment]
@techsavvyash sir I know that this pr itself is not enough to solve the issue .I just wanted to Know if there are any changes you suggest .

**Comment by techsavvyash** [comment]
Hey @vsvishalsharma,
This is PR is not really relevant in any sense to the project, this has a lot of conflicts with the base branch, this does not add the BunJS support to stencil, and we don't require adding BunJS support to samples unless Bun is officially supported by Stencil. The comment where I ask you to try running the samples using Bun was to help you get an understanding of how a Nest project would run using BunJS and then come up with the required changes in the custom components that stencil gives to achieve bun support. I suggest you take up this exercise after a bit more homework and then raise a relevant PR.

**Comment by techsavvyash** [comment]
Hey @vsvishalsharma 
This pull request appears to be somewhat divergent from the project's current focus. It seems to have several conflicts with the base branch, and the addition of BunJS support to Stencil doesn't align with our current priorities, especially since BunJS isn't officially supported by Stencil.

Regarding your attempt to run the samples using BunJS, I appreciate your initiative in exploring how a Nest project would function with BunJS and how we could integrate that with Stencil's custom components. However, it might be beneficial for you to do some additional research and experimentation before submitting a pull request.

In the meantime, let's refocus our efforts on tasks that are more closely aligned with our project goals and priorities. If you have any questions or need further guidance on how to proceed, please feel free to reach out.

**Comment by vsvishalsharma** [comment]
@techsavvyash sir i am sorry for the shortcomings

I appreciate the feedback. Could you provide some guidance on how I can address the conflicts with the base branch and ensure that the pull request aligns better with the project's focus? Additionally, are there specific tasks or areas you suggest I explore further to contribute effectively to the project?

**Comment by techsavvyash** [comment]
Sure @vsvishalsharma,

1. For resolving conflicts: Rebase/merge your PR with the current main and then make the required changes. [[1]](https://medium.com/@knoldus/how-to-resolve-merge-conflicts-in-git-pull-request-pr-e0b4901c9b79) and [[2]](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) might be good references to learn more about resolving conflics.

2. For alignment with the ticket requirements, I'd suggest you run the samples with BunJS and see what all problems are arising and need solving, then you checkout the [schematics](https://github.com/SamagraX-stencil/schematics) repository which keeps the code for the base application and other code injection in a stencil project, to make the relevant changes that you find during your dry run of running the applications with BunJS. Once those changes are made, then you can go to [stencil-cli](https://github.com/SamagraX-stencil/stencil-cli) to make any changes that will be required to incorporate the changes in the [schematics](https://github.com/SamagraX-stencil/schematics).

I'd you approach this ticket in parts:
1. Figure out how to run a basic NestJS app with BunJS. A good reference link for this has been given in #4.
2. Add stencil components in the NestJS app running using Bun from step-1 and see if something fails, in case something fails then figure out how to make them compatible with bun and come up with a Plan of Action (POA) of what all the issues that you encounter and how you are going to solve them.
3. Then take up making the required changes as per the POA in the required repositories, [stencil](https://github.com/SamagraX-stencil/stencil) for the custom made components like `interceptors`, `modules` and `services`, [schematics](https://github.com/SamagraX-stencil/schematics) for the code injection and base application files and other relevant files and [stencil-cli](https://github.com/samagrax-stencil/stencil-cli) to update the `cli` that helps bootstrap stencil applications.


Please feel free to reach out in case of any issues or confusions.

**Comment by vsvishalsharma** [comment]
@techsavvyash sir,
After reviewing the project structure, I believe the following files play a crucial role in ensuring compatibility with BunJS:

-gulpfile.js and related configuration files: These files are pivotal for managing tasks such as building, testing, and running the Stencil project. Adjustments may be necessary to integrate BunJS into these workflows effectively.

-package.json: This file defines various scripts and dependencies essential for project setup, development, and testing. I anticipate that modifications to script definitions may be necessary to incorporate BunJS-specific commands and configurations.

-Test files: Ensuring that our test suite remains compatible with BunJS is crucial for maintaining the reliability and stability of the Stencil project. Modifications to test files may be required to accommodate any changes made for BunJS integration.

However,I want to know whether my understanding aligns with the actual requirements for BunJS integration. Could you please provide guidance on which specific files within the repository are crucial for ensuring compatibility with BunJS, including any test files that may need adjustment? Your insights would be invaluable as I proceed with this integration.

Considering the primary function of the repository in managing code injection into Stencil projects, I'm curious to know if modifications within the src directory are essential for ensuring compatibility with BunJS. Could you please clarify whether adjustments need to be made within this directory, or if the focus should primarily be on other areas of the repository?

**Pull request closed without merging**
