### PR TITLE
added new features

### PR DESCRIPTION
**Pull request by thekavikumar**
Issue: #7
 
https://github.com/SamagraX-Stencil/stencil/assets/50093149/93d54363-ccf6-4807-85c9-1747f2fec041

### CODE REVIEW

**Comment by thekavikumar** [comment]
@techsavvyash please review this PR sir

**Comment by techsavvyash** [comment]
attach a screen recording of the features with the PR please.

**Comment by thekavikumar** [comment]
> Issue: #7
> 
>  vscode.mp4

it is here right

**Comment by techsavvyash** [comment]
> Reference

sorry my bad! :p

**Comment by thekavikumar** [comment]
no prob :)

**Comment by techsavvyash** [comment]
does it handle the cases where the user can change the path for the `schema.prisma`?

**Comment by thekavikumar** [comment]
yes, it will show prisma file path not configured in settings using vscode info

**Comment by techsavvyash** [comment]
what if the user wants to set some other path for a `schema.prisma`? Are we checking for the root level `prisma/schema.prisma` ?

**Comment by thekavikumar** [comment]
> does it handle the cases where the user can change the path for the `schema.prisma`?

the user can change the path too by changing it in settings.json

**Comment by thekavikumar** [comment]
> what if the user wants to set some other path for a `schema.prisma`? Are we checking for the root level `prisma/schema.prisma` ?

we check at root level only sir

**Comment by techsavvyash** [comment]
> > does it handle the cases where the user can change the path for the `schema.prisma`?
> 
> the user can change the path too by changing it in settings.json

add a command palette command for this and that should be good enough to close this PR.

**Comment by thekavikumar** [comment]
sure will add it soon

**Comment by thekavikumar** [comment]
@techsavvyash please review the PR, I've added the command to set prisma path from command pallate too

**Review by techsavvyash — APPROVED** [review]
👍🏼

**Comment by sagarkori143** [comment]
Hey @techsavvyash 👋
Does this PR completely solves the issue #7 ?

**Comment by thekavikumar** [comment]
https://github.com/SamagraX-Stencil/stencil/issues/7#issuecomment-2080356446

**Comment by thekavikumar** [comment]
Fixes: #100

**Pull request merged**
