### PR TITLE
Configured Husky and lint-staged for pre-commit hooks

### LINKED ISSUE #55: [stencil] enforce linting

### PR DESCRIPTION
**Pull request by vsvishalsharma**
fixes #55 

- Added ESLint configuration files
- Added Prettier configuration files
- Configured Husky and lint-staged for pre-commit hooks
- Updated package.json files in relevant directories
- Ensured consistent linting and formatting across the project

### CODE REVIEW

**Comment by vsvishalsharma** [comment]
@techsavvyash please review it ,looking forward to your remarks.

**Comment by techsavvyash** [comment]
Hey @vsvishalsharma,
Thanks for the PR.
While this PR adds linting and code formatting to our repo, the main of the ticket is to enable linting and code formatting setup in the projects that are generated by stencil. It would be great if you could raise a PR on the [SamagraX-stencil/schematics](https://github.com/SamagraX-Stencil/schematics) repo as well, fixing and properly setting up the linting and formatting rules in the base repo.
Feel free to reach out in case of any issues you might face.

**Comment by vsvishalsharma** [comment]
@techsavvyash Sir thank you for your valuable feedback. I appreciate the clarity on the main goal of the ticket. To address the requirements effectively, I'll ensure to add linting to the base repository and enable linting and code formatting setup in projects generated by Stencil.

Adding Linting to the Base Repository:
For the base repository, I'll implement linting and code formatting rules to maintain code quality and consistency. This involves configuring ESLint or a similar linter, defining linting rules, and setting up scripts to run linting and formatting tasks. Additionally, I'll ensure comprehensive documentation on how to set up and use linting in the project.

Enabling Linting and Code Formatting in Stencil Projects:
To enable linting and code formatting setup in projects generated by Stencil, I'll modify the Stencil schematics to include the necessary configurations and scripts. This includes updating project templates to include ESLint and Prettier configurations, configuring package.json scripts for running linting and formatting tasks, and installing required dependencies. I'll thoroughly test these changes to ensure they work as expected.

Once the modifications are complete, I'll raise a pull request on the SamagraX-stencil/schematics repository, providing clear documentation and rationale for the changes made. I'll actively engage with the maintainers to address any feedback or questions during the review process.

Thank you for the opportunity to contribute to this project. Please let me know if you have any further questions or if there's anything specific you'd like me to focus on.

**Comment by vsvishalsharma** [comment]
@techsavvyash sir I have added the pr for same in https://github.com/SamagraX-Stencil/schematics please review it

**Review by techsavvyash — APPROVED** [review]

**Comment by techsavvyash** [comment]
Thanks for the PR @vsvishalsharma

**Pull request merged**
